name: Today I Learned
description: Answers to full-stack dev questions
meta_description: "Stuff I figured out so that you don't have to. Full-stack web development tips, tricks, gotchas, and more"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://peteranglea.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
permalink: :year/:month/:day/:title/

# Details for the RSS feed generator
url:            'https://peteranglea.github.io'
author:         'Peter Anglea'